## 1. SQL

### Brushing up SQL Concepts

Here are the conceps you should brush-up on or learn to have a basic understanding of SQL and complete the assignment:

1. **Basic SQL Queries**  
   - Understanding the `SELECT` statement, filtering with `WHERE`, and limiting results with `LIMIT`.

2. **Sorting and Aggregation**  
   - Using `ORDER BY`, `GROUP BY`, `HAVING` clauses and aggregate functions like `COUNT`, `SUM`, etc.

3. **Joins and Relationships**  
   - Combining data from multiple tables using various joins (e.g., `INNER JOIN`, `LEFT JOIN`, self-joins).

4. **Subqueries and Nested Queries**  
   - Writing queries within queries to filter or compute intermediate results.

5. **Common Table Expressions (CTEs)**  
   - Creating temporary result sets to simplify complex queries.

6. **Window Functions**  
   - Applying functions across a set of rows related to the current row (e.g., `RANK`, `ROW_NUMBER`).

7. **Transactions and Data Manipulation**  
   - Using `UPDATE`, `DELETE`, `INSERT`, and managing transactions with commands like `BEGIN` and `COMMIT`.

8. **String Aggregation**  
   - Techniques to combine multiple row values into a single string (e.g., using `GROUP_CONCAT`).


### Resources
I find the best way to learn is to start with looking up a specific concept and then playing around with it using an actual database (can use the Open Flights DB below). It can be also be helpful to use these interactive SQL learning tools:

- SQL ZOO : https://sqlzoo.net/wiki/SQL_Tutorial
- SQL Tutorial : https://www.w3schools.com/sql/

Here is a website for comprehensive sqlite syntax tutorials: https://www.sqlitetutorial.net/

If you want to build a more foundational knowlegde in SQL and then play with the queries:
- cannot go wrong with freecodecamp: https://www.youtube.com/watch?v=HXV3zeQKqGY

### Setting Up sqlite DB

We are going to be using the open flights database. The following code will download the data and then set up a sqllite DB that will be the basis of the quiz. Feel free to play around with using SQL queries

In [2]:
import sqlite3
import pandas as pd

url_dict = {
'airports' : ('https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat',["Airport ID", "Name","City",'Country','IATA','ICAO','Latitude','Longitude','Altitude',
                                                                                                 'Timezone','DST','Tz database timezone','Type','Source']),
'airlines' : ('https://raw.githubusercontent.com/jpatokal/openflights/master/data/airlines.dat',['Airline ID','Name','Alias','IATA','ICAO','Callsign','Country','Active']),
'routes' : ('https://raw.githubusercontent.com/jpatokal/openflights/master/data/routes.dat',['Airline','Airline ID','Source airport','Source airport ID','Destination airport',
                                                                                             'Destination airport ID','Codeshare','Stops','Equipment']),
'planes' : ('https://raw.githubusercontent.com/jpatokal/openflights/master/data/planes.dat',['Name','IATA code','ICAO code'])
}



conn = sqlite3.connect("openflights.db")
cursor = conn.cursor()

for db_name, (url,columns) in url_dict.items():
    df = pd.read_csv(url,names=columns)
    df.columns = df.columns.str.lower().str.replace(" ", "_")
    print(df)
    df.to_sql(db_name,conn,if_exists='replace',index = False),

      airport_id                                         name          city  \
0              1                               Goroka Airport        Goroka
1              2                               Madang Airport        Madang
2              3                 Mount Hagen Kagamuga Airport   Mount Hagen
3              4                               Nadzab Airport        Nadzab
4              5  Port Moresby Jacksons International Airport  Port Moresby
...          ...                                          ...           ...
7693       14106                          Rogachyovo Air Base        Belaya
7694       14107                        Ulan-Ude East Airport      Ulan Ude
7695       14108                         Krechevitsy Air Base      Novgorod
7696       14109                  Desierto de Atacama Airport       Copiapo
7697       14110                           Melitopol Air Base     Melitopol

               country iata  icao   latitude   longitude  altitude timezone  \
0     Papua New Guinea  GKA  AYGA  -6.081690  145.391998      5282       10
1     Papua New Guinea  MAG  AYMD  -5.207080  145.789001        20       10
2     Papua New Guinea  HGU  AYMH  -5.826790  144.296005      5388       10
3     Papua New Guinea  LAE  AYNZ  -6.569803  146.725977       239       10
4     Papua New Guinea  POM  AYPY  -9.443380  147.220001       146       10
...                ...  ...   ...        ...         ...       ...      ...
7693            Russia   \N  ULDA  71.616699   52.478298       272       \N
7694            Russia   \N  XIUW  51.849998  107.737999      1670       \N
7695            Russia   \N  ULLK  58.625000   31.385000        85       \N
7696             Chile  CPO  SCAT -27.261200  -70.779198       670       \N
7697           Ukraine   \N  UKDM  46.880001   35.305000         0       \N

     dst  tz_database_timezone     type       source
0      U  Pacific/Port_Moresby  airport  OurAirports
1      U  Pacific/Port_Moresby  airport  OurAirports
2      U  Pacific/Port_Moresby  airport  OurAirports
3      U  Pacific/Port_Moresby  airport  OurAirports
4      U  Pacific/Port_Moresby  airport  OurAirports
...   ..                   ...      ...          ...
7693  \N                    \N  airport  OurAirports
7694  \N                    \N  airport  OurAirports
7695  \N                    \N  airport  OurAirports
7696  \N                    \N  airport  OurAirports
7697  \N                    \N  airport  OurAirports

[7698 rows x 14 columns]
      airline_id                                          name  \
0             -1                                       Unknown
1              1                                Private flight
2              2                                   135 Airways
3              3                                 1Time Airline
4              4  2 Sqn No 1 Elementary Flying Training School
...          ...                                           ...
6157       21248                                   GX Airlines
6158       21251                        Lynx Aviation (L3/SSX)
6159       21268                               Jetgo Australia
6160       21270                                  Air Carnival
6161       21317                                 Svyaz Rossiya

                  alias iata icao         callsign         country active
0                    \N    -  NaN               \N              \N      Y
1                    \N    -  NaN              NaN             NaN      Y
2                    \N  NaN  GNL          GENERAL   United States      N
3                    \N   1T  RNX          NEXTIME    South Africa      Y
4                    \N  NaN  WYT              NaN  United Kingdom      N
...                 ...  ...  ...              ...             ...    ...
6157                NaN  NaN  CBG            SPRAY           China      Y
6158                NaN  NaN  SSX           Shasta   United States      N
6159                NaN   JG   \N              NaN       Australia      Y
6160                NaN   2S   \N              NaN           India      Y
6161  Russian Commuter    7R  SJM  RussianConnecty          Russia      Y

[6162 rows x 8 columns]
      airline airline_id source_airport source_airport_id destination_airport  \
0          2B        410            AER              2965                 KZN
1          2B        410            ASF              2966                 KZN
2          2B        410            ASF              2966                 MRV
3          2B        410            CEK              2968                 KZN
4          2B        410            CEK              2968                 OVB
...       ...        ...            ...               ...                 ...
67658      ZL       4178            WYA              6334                 ADL
67659      ZM      19016            DME              4029                 FRU
67660      ZM      19016            FRU              2912                 DME
67661      ZM      19016            FRU              2912                 OSS
67662      ZM      19016            OSS              2913                 FRU

      destination_airport_id codeshare  stops equipment
0                       2990       NaN      0       CR2
1                       2990       NaN      0       CR2
2                       2962       NaN      0       CR2
3                       2990       NaN      0       CR2
4                       4078       NaN      0       CR2
...                      ...       ...    ...       ...
67658                   3341       NaN      0       SF3
67659                   2912       NaN      0       734
67660                   4029       NaN      0       734
67661                   2913       NaN      0       734
67662                   2912       NaN      0       734

[67663 rows x 9 columns]
                                             name iata_code icao_code
0                         Aerospatiale (Nord) 262       ND2      N262
1    Aerospatiale (Sud Aviation) Se.210 Caravelle       CRV      S210
2                    Aerospatiale SN.601 Corvette       NDC      S601
3                  Aerospatiale/Alenia ATR 42-300       AT4      AT43
4                  Aerospatiale/Alenia ATR 42-500       AT5      AT45
..                                            ...       ...       ...
241                                Tupolev Tu-144        \N      T144
242                                Tupolev Tu-154       TU5      T154
243                                Tupolev Tu-204       T20      T204
244                               Yakovlev Yak-40       YK4      YK40
245                               Yakovlev Yak-42       YK2      YK42

[246 rows x 3 columns]

In [66]:
#use multiline queries to make it easier to read nad build
query = """
select * from airlines
"""

query2 = """
select * from routes
"""

df = pd.read_sql_query(query2,conn)
df

,airline,airline_id,source_airport,source_airport_id,destination_airport,destination_airport_id,codeshare,stops,equipment
0,2B,410,AER,2965,KZN,2990,NaN,0,CR2
1,2B,410,ASF,2966,KZN,2990,NaN,0,CR2
2,2B,410,ASF,2966,MRV,2962,NaN,0,CR2
3,2B,410,CEK,2968,KZN,2990,NaN,0,CR2
4,2B,410,CEK,2968,OVB,4078,NaN,0,CR2
...,...,...,...,...,...,...,...,...,...
67658,ZL,4178,WYA,6334,ADL,3341,NaN,0,SF3
67659,ZM,19016,DME,4029,FRU,2912,NaN,0,734
67660,ZM,19016,FRU,2912,DME,4029,NaN,0,734
67661,ZM,19016,FRU,2912,OSS,2913,NaN,0,734
67662,ZM,19016,OSS,2913,FRU,2912,NaN,0,734

### SQL Quiz (Answers)

In [19]:
#1. Retrieve all columns for the first 5 rows from the `airports` table.
query = """
select * from airports
limit 5
"""

df = pd.read_sql_query(query,conn)
df

,airport_id,name,city,country,iata,icao,latitude,longitude,altitude,timezone,dst,tz_database_timezone,type,source
0,1,Goroka Airport,Goroka,Papua New Guinea,GKA,AYGA,-6.081690,145.391998,5282,10,U,Pacific/Port_Moresby,airport,OurAirports
1,2,Madang Airport,Madang,Papua New Guinea,MAG,AYMD,-5.207080,145.789001,20,10,U,Pacific/Port_Moresby,airport,OurAirports
2,3,Mount Hagen Kagamuga Airport,Mount Hagen,Papua New Guinea,HGU,AYMH,-5.826790,144.296005,5388,10,U,Pacific/Port_Moresby,airport,OurAirports
3,4,Nadzab Airport,Nadzab,Papua New Guinea,LAE,AYNZ,-6.569803,146.725977,239,10,U,Pacific/Port_Moresby,airport,OurAirports
4,5,Port Moresby Jacksons International Airport,Port Moresby,Papua New Guinea,POM,AYPY,-9.443380,147.220001,146,10,U,Pacific/Port_Moresby,airport,OurAirports

In [20]:
#2. Select the `name`, `city`, and `country` columns from the `airports` table
#for airports located in the United States.

query = """
select name,city,country from airports
where country = "United States"
"""

df = pd.read_sql_query(query,conn)
df

                                          name             city        country
0                   Barter Island LRRS Airport    Barter Island  United States
1                       Wainwright Air Station  Fort Wainwright  United States
2                   Cape Lisburne LRRS Airport    Cape Lisburne  United States
3                       Point Lay LRRS Airport        Point Lay  United States
4                   Hilo International Airport             Hilo  United States
...                                        ...              ...            ...
1507  Camp Pendleton MCAS (Munn Field) Airport        Oceanside  United States
1508                  Vidalia Regional Airport          Vidalia  United States
1509                 Granbury Regional Airport         Granbury  United States
1510                     Oswego County Airport           Fulton  United States
1511                Mitchell Municipal Airport         Mitchell  United States

[1512 rows x 3 columns]

In [73]:
#3. (Slight Challenge) Find all active airlines (where `active = 'Y'`) 
#that operate from at least 3 distinct source airports. 
#Display the airline's name, airline_id, and the count of distinct source airports. 
#Order the results by the count (highest first). 
query = r"""
select  a.name, a.airline_id, count(distinct r.source_airport) as source_cnt 
from airlines a,routes r
where a.airline_id = r.airline_id 
    and a.active = 'Y' 
    and source_airport_id != '\N' 
group by r.airline_id 
having source_cnt >= 3 
order by source_cnt DESC
"""

df = pd.read_sql_query(query,conn)
df

                                 name  airline_id  source_cnt
0                   American Airlines          24         428
1                     United Airlines        5209         426
2                          Air France         137         377
3            KLM Royal Dutch Airlines        3090         360
4                          US Airways        5265         348
..                                ...         ...         ...
496                       Starline.kz       11963           3
497  Compagnie Africaine d\\'Aviation       11806           3
498         Atlantis European Airways        1048           3
499                 Albanian Airlines        1008           3
500                       40-Mile Air          10           3

[501 rows x 3 columns]

In [3]:
#4. List all airports that serve as a source airport along with their name, city,
# country, altitude, and the total number of routes departing from that airport. 
# Only include airports with at least one departing route. 
# Order the results by the total number of routes (descending) and 
# then by altitude (descending).

query = """
select r.source_airport, a.city, a.country, a.altitude, count(r.source_airport_id) as routes_cnt
from airports a, routes r 
where r.source_airport_id = a.airport_id
group by r.source_airport_id having routes_cnt >= 1
order by routes_cnt DESC, a.altitude DESC
"""

df = pd.read_sql_query(query,conn)
df

     source_airport              city          country  altitude  routes_cnt
0               ATL           Atlanta    United States      1026         915
1               ORD           Chicago    United States       672         558
2               PEK           Beijing            China       116         535
3               LHR            London   United Kingdom        83         527
4               CDG             Paris           France       392         524
...             ...               ...              ...       ...         ...
3206            ELV        Elfin Cove    United States         0           1
3207            HYG          Hydaburg    United States         0           1
3208            SPB  Charlotte Amalie   Virgin Islands         0           1
3209            ULO          Ulaangom         Mongolia         0           1
3210            CHY      Choiseul Bay  Solomon Islands         0           1

[3211 rows x 5 columns]

In [13]:
#5. List each source airport along with the count of routes departing from it and 
#its rank based on the route count (with the highest count ranked 1). 
#Only include airports with at least 5 routes.
query = """
select source_airport, 
       count(source_airport_id) as route_count,
       rank() over(order by count(source_airport_id) DESC) as rank
from routes
group by source_airport
having route_count >= 5
"""


df = pd.read_sql_query(query,conn)
df

     source_airport  route_count  rank
0               ATL          915     1
1               ORD          558     2
2               PEK          535     3
3               LHR          527     4
4               CDG          524     5
...             ...          ...   ...
1504            ARI            5  1343
1505            APW            5  1343
1506            AOR            5  1343
1507            AOJ            5  1343
1508            AGM            5  1343

[1509 rows x 3 columns]

In [40]:
#6. (Slight Challenge) List each route's details including the airline name and 
# airline country, the source airport name and city, and the destination airport name and city.
# Only include routes where both the source and destination airports are located in the same country as the airline.

query = """
select r.airline, al.country, r.source_airport,sa.city, r.destination_airport, da.city
from routes r, airlines al, airports sa, airports da
where r.airline_id = al.airline_id
and r.source_airport_id = sa.airport_id
and r.destination_airport_id = da.airport_id
and sa.country = da.country
"""

df = pd.read_sql_query(query,conn)
df

,airline,country,source_airport,city,destination_airport,city
0,2B,Portugal,AER,Sochi,KZN,Kazan
1,2B,Portugal,ASF,Astrakhan,KZN,Kazan
2,2B,Portugal,ASF,Astrakhan,MRV,Mineralnye Vody
3,2B,Portugal,CEK,Chelyabinsk,KZN,Kazan
4,2B,Portugal,CEK,Chelyabinsk,OVB,Novosibirsk
...,...,...,...,...,...,...
31638,ZL,Australia,WIN,Winton,LRE,Longreach
31639,ZL,Australia,WIN,Winton,TSV,Townsville
31640,ZL,Australia,WYA,Whyalla,ADL,Adelaide
31641,ZM,United States,FRU,Bishkek,OSS,Osh
31642,ZM,United States,OSS,Osh,FRU,Bishkek

In [48]:
#7. Find all airports that do not appear in the routes table at all (neither as a source nor 
#as a destination). List the airport's name, city, and country.
query = """
select name,city,country
from airports
where airport_id not in (select source_airport_id from routes)
and airport_id not in (select destination_airport_id from routes)
"""

df = pd.read_sql_query(query,conn)
df

                             name            city  country
0            Hornafjörður Airport            Hofn  Iceland
1                 Húsavík Airport         Husavik  Iceland
2          Patreksfjörður Airport  Patreksfjordur  Iceland
3            Siglufjörður Airport    Siglufjordur  Iceland
4          Vestmannaeyjar Airport  Vestmannaeyjar  Iceland
...                           ...             ...      ...
4472          Rogachyovo Air Base          Belaya   Russia
4473        Ulan-Ude East Airport        Ulan Ude   Russia
4474         Krechevitsy Air Base        Novgorod   Russia
4475  Desierto de Atacama Airport         Copiapo    Chile
4476           Melitopol Air Base       Melitopol  Ukraine

[4477 rows x 3 columns]

In [61]:
#8. List each source airport once along with a comma-separated 
#list of all its distinct destination airports. 
# Only include source airports that have multiple distinct destination airports.

query = """
select source_airport, group_concat(distinct destination_airport) as destination_airports
from routes
group by source_airport
having count(distinct destination_airport) > 1
"""

df = pd.read_sql_query(query,conn)
df

     source_airport                               destination_airports
0               AAE                        ALG,CDG,IST,LYS,MRS,ORN,ORY
1               AAL  AMS,AAR,OSL,BLL,SVG,AGP,ALC,CPH,LGW,PMI,BCN,AR...
2               AAN                                            CCJ,PEW
3               AAQ                                        DME,LED,SVO
4               AAR                    AAL,BMA,GOT,OSL,AGP,PMI,STN,CPH
...             ...                                                ...
2498            ZTH    ATH,DUS,MUC,VIE,MAN,CRL,EFL,KIT,BRU,AMS,LBA,LGW
2499            ZUH  CZX,HAK,PVG,SHA,SYX,TSN,CKG,CTU,FOC,HYN,KHN,KW...
2500            ZUM                                            YWK,YYR
2501            ZVK                                        BKK,PKZ,VTE
2502            ZYI  KMG,SHA,PEK,CAN,SZX,CTU,CSX,HAK,SYX,XIY,XMN,NK...

[2503 rows x 2 columns]

In [72]:
#9. Update the `active` status to `'N'` for the airline with a specific `airline_id` 
#(e.g., `1234`) in the `airlines` table.

cursor.execute("update airlines set active = 'N' where airline_id = 1")
conn.commit()

query1 = """
select active from airlines where airline_id = 1
"""

df = pd.read_sql_query(query1,conn)
df

  active
0      N

In [81]:
#10. Create a SQL transaction that deletes all routes from the `routes` table where `stops` is
# greater than 0, commits the transaction, and then verifies that no routes with `stops` 
#greater than 0 remain.

cursor.execute("delete from routes where stops > 0")
conn.commit()

query = """
select * from routes where stops > 0
"""

df = pd.read_sql_query(query,conn)
df

Empty DataFrame
Columns: [airline, airline_id, source_airport, source_airport_id, destination_airport, destination_airport_id, codeshare, stops, equipment]
Index: []

### SQL Quiz

*All questions require SQL queries, statements, or transactions. Provide your answers as SQL code.*

1. Retrieve all columns for the first 5 rows from the `airports` table.
2. Select the `name`, `city`, and `country` columns from the `airports` table for airports located in the United States.
3. (Slight Challenge) Find all active airlines (where `active = 'Y'`) that operate from at least 3 distinct source airports. Display the airline's name, airline_id, and the count of distinct source airports. Order the results by the count (highest first). 
4. List all airports that serve as a source airport along with their name, city, country, altitude, and the total number of routes departing from that airport. Only include airports with at least one departing route. Order the results by the total number of routes (descending) and then by altitude (descending).
5. List each source airport along with the count of routes departing from it and its rank based on the route count (with the highest count ranked 1). Only include airports with at least 5 routes.
6. (Slight Challenge) List each route's details including the airline name and airline country, the source airport name and city, and the destination airport name and city. Only include routes where both the source and destination airports are located in the same country as the airline.
7. Find all airports that do not appear in the routes table at all (neither as a source nor as a destination). List the airport's name, city, and country.
8. List each source airport once along with a comma-separated list of all its distinct destination airports. Only include source airports that have multiple distinct destination airports.
9. Update the `active` status to `'N'` for the airline with a specific `airline_id` (e.g., `1234`) in the `airlines` table.
10. Create a SQL transaction that deletes all routes from the `routes` table where `stops` is greater than 0, commits the transaction, and then verifies that no routes with `stops` greater than 0 remain.

## 2. Workflow for Assignment Submission

You will create your own repository on GitHub and then upload your assignments by directly pushing to the repo. This approach avoids merge conflicts with files such as IPython Notebook files and keeps your work isolated.

### Workflow Overview

1. Create a Repo On Github  
2. Clone Your Repo Locally  
3. Set Up the Upstream Remote (`git clone` will also do this, just verify)
4. Add any changes and commit
5. Pull any changes in the repo not in local copy (`git pull --rebase`)
6. Push changes

---

### 1. Make your own GitHib Repo

Name it what you like. data-alchemy-assignments doesn't sound too bad 

---

### 2. Clone Your Repo Locally

Open your terminal and run:

`git clone https://github.com/your-username/your-repo.git`

Then change into the repository directory:

`cd your-repo`

---

### 3. Set Up the Upstream Remote

Above step should accomplish this

Verify your remotes with:

`git remote -v`

You should see two remotes:
- **origin** pointing to your repo

---

### 4. Work on and Commit Your Assignment

Add the file to your local checkout from my emails.
Edit the assignment files as needed. When you are ready to save your work, add and commit your changes:

`git add .`  
`git commit -m "Completed week2 assignment: brief description of changes"`

---

### 5. Update Your Local Master with Upstream Changes

If you have made any changes in your master branch, you can stash them before pulling. To stash your changes, run:

`git stash`

*Remember, dont push changes to your master as it will create merge conflicts when you try to pull new changes from the upstream (Pratyush's Assignments repo)*


Then, fetch the latest changes from upstream:

`git fetch upstream`

If you stashed changes earlier and want to reapply them after updating master, run:

`git stash pop`

*Note: Stashing ensures that any local modifications on your master branch do not conflict with the updates you are pulling from upstream.*

---

### 6. Push Your Assignment Branch to Your Fork

Push your branch to your fork on GitHub:

`git push origin assignment-week2`

---

### Tips

- **Stashing Local Changes:**  
  Always stash any uncommitted changes in your master branch before fetching and merging upstream updates to avoid merge conflicts.

## 3. Additional Tasks

1. How would you put your Build Project experience in your resume?

    I would add the project title and describe the technical skills I applied, such as Git, Python, and working with datasets. Additionally, I would describe my soft skills by explaining how we communicated and met once a week to report on the progress of our individual projects, as well as to discuss and exchange ideas and information.

2. List 3-5 datasets that you would choose from for your final project. This is your chance to pick something in a topic that interests you. We will cover how to find datasets in next session.

   When it comes to finding datasets, I can only think of the Kaggle website. 
   
   The following are datasets I might use for the project:
   
   1. Retail Store Product Sales Dataset Analysis
   2. Parental Genetics & Child Trait Prediction Dataset
   3. Tech Salary & Skills Dataset
   4. Internship Scam Detection Dataset